"""Bake low-polygon city silhouette sectors from the Key West preview data."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[2]
CITY_PATH = ROOT / "data/world/key_west/city_preview.json"
HEIGHT_PATH = ROOT / "world/terrain/key_west_preview_2m_la8.png"
HEIGHT_META_PATH = ROOT / "world/terrain/key_west_preview_2m_la8.json"
OUTPUT = ROOT / "data/world/key_west/far_city"


class HeightMap:
    def __init__(self, path: Path, meta: dict):
        self.image = Image.open(path).convert("LA")
        self.origin_x = float(meta["origin_x"])
        self.origin_z = float(meta["origin_z"])
        self.m_per_px = float(meta["m_per_px"])
        self.height_min = float(meta["height_min"])
        self.height_max = float(meta["height_max"])

    def sample(self, x: float, z: float) -> float:
        px = (x - self.origin_x) / self.m_per_px
        pz = (z - self.origin_z) / self.m_per_px
        px = min(max(px, 0.0), self.image.width - 1.0)
        pz = min(max(pz, 0.0), self.image.height - 1.0)
        x0, z0 = int(px), int(pz)
        x1, z1 = min(x0 + 1, self.image.width - 1), min(z0 + 1, self.image.height - 1)
        tx, tz = px - x0, pz - z0

        def decode(ix: int, iz: int) -> float:
            luminance, alpha = self.image.getpixel((ix, iz))
            encoded = luminance * 256 + alpha
            return self.height_min + encoded / 65535.0 * (self.height_max - self.height_min)

        top = decode(x0, z0) * (1.0 - tx) + decode(x1, z0) * tx
        bottom = decode(x0, z1) * (1.0 - tx) + decode(x1, z1) * tx
        return max(0.0, top * (1.0 - tz) + bottom * tz)


def box_vertices(
    proxy: dict, y: float, height: float, chunk_origin: tuple[float, float]
) -> list[tuple[float, float, float]]:
    x, z = float(proxy["x"]), float(proxy["z"])
    width = max(float(proxy.get("width", 2.5)), 2.5) * 0.5
    depth = max(float(proxy.get("depth", 2.5)), 2.5) * 0.5
    angle = float(proxy.get("angle", 0.0))
    cosine, sine = math.cos(angle), math.sin(angle)
    ring = [(-width, -depth), (width, -depth), (width, depth), (-width, depth)]
    bottom = [
        (x + cosine * lx + sine * lz - chunk_origin[0], y - 0.3,
         z - sine * lx + cosine * lz - chunk_origin[1])
        for lx, lz in ring
    ]
    top = [(vx, y + height, vz) for vx, _, vz in bottom]
    return bottom + top


def clip_segment(a: tuple[float, float], b: tuple[float, float], bounds: tuple[float, float, float, float]):
    dx, dz = b[0] - a[0], b[1] - a[1]
    t_min, t_max = 0.0, 1.0
    x_min, z_min, x_max, z_max = bounds
    for p, q in ((-dx, a[0] - x_min), (dx, x_max - a[0]), (-dz, a[1] - z_min), (dz, z_max - a[1])):
        if abs(p) < 1e-9:
            if q < 0.0:
                return None
            continue
        t = q / p
        if p < 0.0:
            t_min = max(t_min, t)
        else:
            t_max = min(t_max, t)
        if t_min > t_max:
            return None
    return ((a[0] + dx * t_min, a[1] + dz * t_min), (a[0] + dx * t_max, a[1] + dz * t_max))


def bake() -> tuple[int, int]:
    city = json.loads(CITY_PATH.read_text(encoding="utf-8"))
    meta = json.loads(HEIGHT_META_PATH.read_text(encoding="utf-8"))
    heights = HeightMap(HEIGHT_PATH, meta)
    OUTPUT.mkdir(parents=True, exist_ok=True)
    (OUTPUT / "far_city.mtl").write_text(
        "newmtl massing\nKa 0.48 0.51 0.53\nKd 0.48 0.51 0.53\nKs 0.05 0.05 0.05\nNs 12\n"
        "newmtl road\nKa 0.13 0.14 0.15\nKd 0.13 0.14 0.15\nKs 0.02 0.02 0.02\nNs 4\n"
        "newmtl asphalt\nKa 0.18 0.19 0.20\nKd 0.18 0.19 0.20\nKs 0.02 0.02 0.02\nNs 4\n",
        encoding="ascii",
    )
    chunks = city.get("chunks", {})
    buildings = city.get("buildings", [])
    roads = city.get("roads", [])
    airport_features = city.get("airport_features", [])
    written = 0
    total = 0
    for chunk_id, chunk in chunks.items():
        ids = chunk.get("building_ids", [])
        airport_ids = chunk.get("airport_feature_ids", [])
        if not ids and not airport_ids:
            continue
        output_path = OUTPUT / (chunk_id.replace(":", "_") + ".obj")
        lines = [
            "# Baked ultra-low Key West silhouette; generated by bake_key_west_far_city.py",
            "mtllib far_city.mtl",
            "usemtl massing",
        ]
        origin = (
            float(chunk["origin"][0]) + float(chunk.get("size_m", city.get("chunk_size_m", 512.0))) * 0.5,
            float(chunk["origin"][1]) + float(chunk.get("size_m", city.get("chunk_size_m", 512.0))) * 0.5,
        )
        vertex_offset = 1
        for building_id in ids:
            building = buildings[int(building_id)]
            proxy = building.get("proxy", {})
            if not proxy:
                continue
            base = heights.sample(float(proxy["x"]), float(proxy["z"]))
            height = max(float(building.get("height", 3.0)), 3.0)
            vertices = box_vertices(proxy, base, height, origin)
            lines.extend("v %.3f %.3f %.3f" % vertex for vertex in vertices)
            for face in ((8, 7, 6, 5), (1, 2, 6, 5), (2, 3, 7, 6), (3, 4, 8, 7), (4, 1, 5, 8)):
                ids_text = " ".join(str(vertex_offset + index - 1) for index in face)
                lines.append("f " + ids_text)
            vertex_offset += 8
            total += 1
        chunk_size = float(chunk.get("size_m", city.get("chunk_size_m", 512.0)))
        x_min, z_min = float(chunk["origin"][0]), float(chunk["origin"][1])
        x_max, z_max = x_min + chunk_size, z_min + chunk_size
        lines.append("usemtl road")
        for segment in chunk.get("road_segments", []):
            road_id = int(segment.get("road_id", -1))
            if road_id < 0 or road_id >= len(roads):
                continue
            road = roads[road_id]
            a_values, b_values = segment.get("a", []), segment.get("b", [])
            if len(a_values) < 2 or len(b_values) < 2:
                continue
            clipped = clip_segment(
                (float(a_values[0]), float(a_values[1])),
                (float(b_values[0]), float(b_values[1])),
                (x_min, z_min, x_max, z_max),
            )
            if clipped is None:
                continue
            a, b = clipped
            dx, dz = b[0] - a[0], b[1] - a[1]
            length = math.hypot(dx, dz)
            if length < 0.25:
                continue
            half_width = max(float(road.get("width", 4.0)) * 0.5, 1.0)
            sx, sz = -dz / length * half_width, dx / length * half_width
            ring = (
                (a[0] + sx, a[1] + sz), (b[0] + sx, b[1] + sz),
                (b[0] - sx, b[1] - sz), (a[0] - sx, a[1] - sz),
            )
            for px, pz in ring:
                lines.append(
                    "v %.3f %.3f %.3f"
                    % (px - origin[0], heights.sample(px, pz) + 0.12, pz - origin[1])
                )
            lines.append(
                "f %d %d %d %d"
                % (vertex_offset, vertex_offset + 1, vertex_offset + 2, vertex_offset + 3)
            )
            vertex_offset += 4
        lines.append("usemtl asphalt")
        for feature_id in airport_ids:
            feature = airport_features[int(feature_id)]
            if feature.get("is_area") or feature.get("kind") not in {
                "runway", "taxiway", "taxilane", "stopway", "arrestor_bed"
            }:
                continue
            points = feature.get("points", [])
            half_width = max(float(feature.get("width", 10.0)) * 0.5, 2.0)
            for start, end in zip(points, points[1:]):
                clipped = clip_segment(
                    (float(start[0]), float(start[1])),
                    (float(end[0]), float(end[1])),
                    (x_min, z_min, x_max, z_max),
                )
                if clipped is None:
                    continue
                a, b = clipped
                dx, dz = b[0] - a[0], b[1] - a[1]
                length = math.hypot(dx, dz)
                if length < 0.25:
                    continue
                sx, sz = -dz / length * half_width, dx / length * half_width
                ring = ((a[0] + sx, a[1] + sz), (b[0] + sx, b[1] + sz),
                        (b[0] - sx, b[1] - sz), (a[0] - sx, a[1] - sz))
                for px, pz in ring:
                    lines.append(
                        "v %.3f %.3f %.3f"
                        % (px - origin[0], heights.sample(px, pz) + 0.16, pz - origin[1])
                    )
                lines.append(
                    "f %d %d %d %d"
                    % (vertex_offset, vertex_offset + 1, vertex_offset + 2, vertex_offset + 3)
                )
                vertex_offset += 4
        output_path.write_text("\n".join(lines) + "\n", encoding="ascii")
        written += 1
    return written, total


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    sectors, buildings = bake()
    print(f"Baked {sectors} far-city sectors containing {buildings} low-poly buildings into {OUTPUT}")


if __name__ == "__main__":
    main()
